#!/usr/bin/env bash
# configuring webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo mkdir -p /var/www/html
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo touch /var/www/html/404.html
sudo bash -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
sudo bash -c "printf %s \"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}\" > /etc/nginx/sites-available/default"

sudo service nginx restart
