#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy=2.0.\*
sudo bash -c "echo -e \"ENABLED=1\n\" >> /etc/default/haproxy"
sudo bash -c "echo \"frontend web-front
        bind *:80
        default_backend web-backend
        
backend web-backend
        balance roundrobin
        server 362535-web-01 52.91.126.18:80 check
        server 362535-web-02 100.26.244.46:80 check\" >> /etc/haproxy/haproxy.cfg"
sudo service haproxy restart
