#!/usr/bin/env bash
# debugging Ubuntu container’s Nginx installation

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
