#!/usr/bin/env bash
# this file prints Best School 10 times using while.
i="1"

while [ $i -lt 101 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
        then
                echo "Fizz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
