#!/usr/bin/env bash
# this file prints Best School 10 times using while.
i="0"
j="0"

while [ $i -ne 13 ]
do
	echo "Hour: $((i))"
	j="0"
	while [ $j -ne 60 ]
	do
		echo "$((j))"
		j=$((j+1))
	done
	i=$((i+1))
done
